// Proposal-aware writer for the phase-1 entity tables.
//
// Editors that handle entities in the content-proposals allowlist
// (tags, tag_groups, spell_rules, spell_rule_applications,
// class_spell_lists) should write through `useEntityWriter` instead
// of calling `upsertDocument` / `deleteDocument` directly. The hook
// inspects `effectiveProfile` and routes the call:
//
//   - `admin` → direct write through the existing d1 helpers.
//   - holder of the additive `content-creator` permission → POST to
//     `/api/proposals`. The change goes into the queue for an admin
//     to approve; the live row is unchanged until then.
//   - anyone else → read-only; methods throw.
//
// The contract intentionally mirrors `upsertDocument` /
// `deleteDocument` so a call site only changes which helper it
// imports, plus optional `{ notes }` for reviewer context.

import { useMemo } from 'react';
import { auth } from './firebase';
import { upsertDocument, deleteDocument } from './d1';

export type ProposalEntityType =
  | 'tag'
  | 'tag_group'
  | 'spell_rule'
  | 'spell_rule_application'
  | 'class_spell_list';

// `entity_type` → camelCase collection name used by the d1 helpers
// (which map to snake_case D1 tables internally).
const ENTITY_TO_COLLECTION: Record<ProposalEntityType, string> = {
  tag: 'tags',
  tag_group: 'tagGroups',
  spell_rule: 'spellRules',
  spell_rule_application: 'spellRuleApplications',
  class_spell_list: 'classSpellLists',
};

export type WriterMode = 'direct' | 'proposal' | 'readonly';

export type WriterApi = {
  mode: WriterMode;
  /**
   * Insert a new row. `id` may be pre-generated by the caller (most
   * editors pre-mint a UUID) or omitted to let the server pick one.
   * Returns the resolved id.
   *
   * In `proposal` mode the row is NOT created yet — the proposer's
   * proposed_payload is recorded in `pending_revisions` and an admin
   * has to approve before it lands.
   */
  create: (
    payload: Record<string, any> & { id?: string },
    opts?: { notes?: string },
  ) => Promise<{ id: string }>;
  /**
   * Update an existing row by id. In `proposal` mode the live row is
   * untouched until an admin approves.
   */
  update: (
    id: string,
    payload: Record<string, any>,
    opts?: { notes?: string },
  ) => Promise<void>;
  /**
   * Delete a row by id. In `proposal` mode the live row is untouched
   * until an admin approves.
   */
  remove: (id: string, opts?: { notes?: string }) => Promise<void>;
};

export function useEntityWriter(
  entityType: ProposalEntityType,
  effectiveProfile: any,
): WriterApi {
  const mode: WriterMode = useMemo(() => {
    if (!effectiveProfile) return 'readonly';
    if (effectiveProfile.role === 'admin') return 'direct';
    if (
      effectiveProfile.permissions &&
      Object.prototype.hasOwnProperty.call(effectiveProfile.permissions, 'content-creator')
    ) {
      return 'proposal';
    }
    return 'readonly';
  }, [effectiveProfile]);

  return useMemo<WriterApi>(() => {
    const collection = ENTITY_TO_COLLECTION[entityType];

    if (mode === 'readonly') {
      const denied = (op: string) => async () => {
        throw new Error(`Read-only context: ${op} is not permitted.`);
      };
      return {
        mode,
        create: denied('create') as any,
        update: denied('update') as any,
        remove: denied('remove') as any,
      };
    }

    if (mode === 'direct') {
      return {
        mode,
        create: async (payload) => {
          const id = payload.id ?? crypto.randomUUID();
          const { id: _drop, ...rest } = payload;
          await upsertDocument(collection, id, rest);
          return { id };
        },
        update: async (id, payload) => {
          await upsertDocument(collection, id, payload);
        },
        remove: async (id) => {
          await deleteDocument(collection, id);
        },
      };
    }

    // proposal mode
    const submitProposal = async (
      op: 'create' | 'update' | 'delete',
      entityId: string | null,
      payload: any | null,
      notes: string | undefined,
    ) => {
      const idToken = await auth.currentUser?.getIdToken();
      if (!idToken) throw new Error('Not signed in.');
      const res = await fetch('/api/proposals', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${idToken}`,
        },
        body: JSON.stringify({
          revisions: [
            {
              entity_type: entityType,
              entity_id: entityId,
              operation: op,
              proposed_payload: payload,
              notes_from_proposer: notes ?? null,
            },
          ],
        }),
      });
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.error || `Proposal failed (HTTP ${res.status})`);
      }
    };

    return {
      mode,
      create: async (payload, opts) => {
        const id = payload.id ?? crypto.randomUUID();
        await submitProposal('create', null, { ...payload, id }, opts?.notes);
        return { id };
      },
      update: async (id, payload, opts) => {
        await submitProposal('update', id, payload, opts?.notes);
      },
      remove: async (id, opts) => {
        await submitProposal('delete', id, null, opts?.notes);
      },
    };
  }, [mode, entityType]);
}

/**
 * Helper for the toast / status text after a mutation, so call sites
 * don't have to repeat the same conditional everywhere. e.g.
 *
 *   await writer.update(id, payload);
 *   toast.success(actionLabel(writer.mode, 'updated'));
 *   // → admin: "Tag updated"
 *   // → content-creator: "Update submitted for review"
 */
export function actionLabel(
  mode: WriterMode,
  pastTense: string,
): string {
  if (mode === 'proposal') {
    return `${capitalize(pastTense.replace(/d$/, ''))} submitted for review`;
  }
  return capitalize(pastTense);
}

function capitalize(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}
