// Proposal-aware writer for the phase-1 entity tables.
//
// Editors that handle entities in the content-proposals allowlist
// (tags, tag_groups, spell_rules, spell_rule_applications,
// class_spell_lists) should write through `useEntityWriter` instead
// of calling `upsertDocument` / `deleteDocument` directly. The hook
// inspects `effectiveProfile` and routes the call:
//
//   - `admin` → direct write through the existing d1 helpers.
//   - holder of the additive `content-creator` permission → POST to
//     `/api/proposals`. The change goes into the queue for an admin
//     to approve; the live row is unchanged until then.
//   - anyone else → read-only; methods throw.
//
// The contract intentionally mirrors `upsertDocument` /
// `deleteDocument` so a call site only changes which helper it
// imports, plus optional `{ notes }` for reviewer context.

import { useMemo } from 'react';
import { toast } from 'sonner';
import { auth } from './firebase';
import { upsertDocument, deleteDocument } from './d1';

export type ProposalEntityType =
  | 'tag'
  | 'tag_group'
  | 'spell_rule'
  | 'spell_rule_application'
  | 'spell'
  | 'class'
  | 'subclass'
  | 'feat'
  | 'item'
  | 'unique_option_group'
  | 'unique_option_item';

// `entity_type` → camelCase collection name used by the d1 helpers
// (which map to snake_case D1 tables internally).
const ENTITY_TO_COLLECTION: Record<ProposalEntityType, string> = {
  tag: 'tags',
  tag_group: 'tagGroups',
  spell_rule: 'spellRules',
  spell_rule_application: 'spellRuleApplications',
  spell: 'spells',
  class: 'classes',
  subclass: 'subclasses',
  feat: 'feats',
  item: 'items',
  unique_option_group: 'uniqueOptionGroups',
  unique_option_item: 'uniqueOptionItems',
};

// `block` mode is wrapper-owned — when a write happens inside a
// <ProposalEditorWrapper>, useProposalAccumulator returns a queue-
// based writer whose mode is `'proposal'`; the wrapper itself flushes
// the queue into the active block at Save-Progress time. We keep
// `'block'` in the union for back-compat with existing call-site
// `mode === 'block'` checks but useEntityWriter never produces it.
export type WriterMode = 'direct' | 'proposal' | 'block' | 'readonly';

export type WriterApi = {
  mode: WriterMode;
  /**
   * Insert a new row. `id` may be pre-generated by the caller (most
   * editors pre-mint a UUID) or omitted to let the server pick one.
   * Returns the resolved id.
   *
   * In `proposal` mode the row is NOT created yet — the proposer's
   * proposed_payload is recorded in `pending_revisions` and an admin
   * has to approve before it lands.
   */
  create: (
    payload: Record<string, any> & { id?: string },
    opts?: { notes?: string },
  ) => Promise<{ id: string }>;
  /**
   * Update an existing row by id. In `proposal` mode the live row is
   * untouched until an admin approves.
   */
  update: (
    id: string,
    payload: Record<string, any>,
    opts?: { notes?: string },
  ) => Promise<void>;
  /**
   * Delete a row by id. In `proposal` mode the live row is untouched
   * until an admin approves.
   */
  remove: (id: string, opts?: { notes?: string }) => Promise<void>;
};

export function useEntityWriter(
  entityType: ProposalEntityType,
  effectiveProfile: any,
): WriterApi {
  const mode: WriterMode = useMemo(() => {
    if (!effectiveProfile) return 'readonly';
    if (effectiveProfile.role === 'admin') return 'direct';
    if (
      effectiveProfile.permissions &&
      Object.prototype.hasOwnProperty.call(effectiveProfile.permissions, 'content-creator')
    ) {
      return 'proposal';
    }
    return 'readonly';
  }, [effectiveProfile]);

  // NOTE: this hook used to auto-promote `direct` → `block` whenever
  // a block was open globally (via useBlock().activeBundleId), so that
  // admin-direct writes would land in the open block. That leaked
  // proposal/block UI onto every admin-direct editor route (cascade
  // banners, drafted-row highlights, "added to block" toasts) the
  // moment an admin had a block open elsewhere. Block-mode writes are
  // now exclusively wrapper-owned: useProposalAccumulator wraps this
  // writer when mounted inside <ProposalEditorWrapper> and queues
  // writes for the wrapper's flushToBundle pipeline. Outside the
  // wrapper, writes always go DIRECT.

  return useMemo<WriterApi>(() => {
    const collection = ENTITY_TO_COLLECTION[entityType];

    if (mode === 'readonly') {
      const denied = (op: string) => async () => {
        throw new Error(`Read-only context: ${op} is not permitted.`);
      };
      return {
        mode,
        create: denied('create') as any,
        update: denied('update') as any,
        remove: denied('remove') as any,
      };
    }

    if (mode === 'direct') {
      return {
        mode,
        create: async (payload) => {
          const id = payload.id ?? crypto.randomUUID();
          const { id: _drop, ...rest } = payload;
          await upsertDocument(collection, id, rest);
          return { id };
        },
        update: async (id, payload) => {
          await upsertDocument(collection, id, payload);
        },
        remove: async (id) => {
          await deleteDocument(collection, id);
        },
      };
    }

    // Standalone-proposal submission for content-creators on non-
    // wrapper routes. Drafts/block writes happen via the wrapper's
    // queue + flushToBundle path — they never come through here.
    const submitProposal = async (
      op: 'create' | 'update' | 'delete',
      entityId: string | null,
      payload: any | null,
      notes: string | undefined,
    ) => {
      const idToken = await auth.currentUser?.getIdToken();
      if (!idToken) throw new Error('Not signed in.');
      const body: Record<string, any> = {
        revisions: [
          {
            entity_type: entityType,
            entity_id: entityId,
            operation: op,
            proposed_payload: payload,
            notes_from_proposer: notes ?? null,
          },
        ],
      };
      const res = await fetch('/api/proposals', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${idToken}`,
        },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const respBody = await res.json().catch(() => ({}));
        throw new Error(respBody.error || `Proposal failed (HTTP ${res.status})`);
      }
    };

    return {
      mode,
      create: async (payload, opts) => {
        const id = payload.id ?? crypto.randomUUID();
        await submitProposal('create', null, { ...payload, id }, opts?.notes);
        return { id };
      },
      update: async (id, payload, opts) => {
        await submitProposal('update', id, payload, opts?.notes);
      },
      remove: async (id, opts) => {
        await submitProposal('delete', id, null, opts?.notes);
      },
    };
  }, [mode, entityType]);
}

/**
 * Helper for the toast / status text after a mutation, so call sites
 * don't have to repeat the same conditional everywhere. e.g.
 *
 *   await writer.update(id, payload);
 *   toast.success(actionLabel(writer.mode, 'updated'));
 *   // → admin: "Tag updated"
 *   // → content-creator: "Update submitted for review"
 */
export function actionLabel(
  mode: WriterMode,
  pastTense: string,
): string {
  if (mode === 'proposal') {
    return `${capitalize(pastTense.replace(/d$/, ''))} submitted for review`;
  }
  if (mode === 'block') {
    return `${capitalize(pastTense.replace(/d$/, ''))} added to block`;
  }
  return capitalize(pastTense);
}

function capitalize(s: string): string {
  if (!s) return s;
  return s[0].toUpperCase() + s.slice(1);
}

/**
 * Narrow helper for the `if (isCreate) writer.create else writer.update` +
 * actionLabel toast pattern. Every editor's handleSave has the same six
 * lines. Helper does the queue/upsert call + emits a mode-aware toast
 * (admin: "X created"; content-creator: "Create submitted for review";
 * block: "Create added to block").
 *
 * The helper does NOT manage the local `pendingCreateId` state — that
 * belongs at the callsite (it depends on whether the editor is single-
 * work or catalog). Single-work editors typically do:
 *
 *   const isCreate = !effectiveId;
 *   await applyProposalWrite(writer, payload, {
 *     id: saveId,
 *     isCreate,
 *     silent,
 *     submitNow: proposalContext?.submitNow,
 *   });
 *   if (isCreate) recordCreate(saveId);
 *
 * Catalog editors do the same minus `recordCreate` (they call
 * `setEditingId(saveId)` instead).
 *
 * Auto-flush: pass `proposalContext.submitNow` in `opts.submitNow` and
 * the helper calls it after queueing (silently — the per-entity toast
 * is the user-visible confirmation). This collapses "Save Spell" +
 * "Save Progress" into one click — see the user-feedback note in
 * docs/handoff-post-dry-pass-2026-05-21.md (Prod #5). When the helper
 * is called from a silent path (pre-flush, auto-stage-on-switch) the
 * flush is skipped automatically because the wrapper's own flushToBundle
 * is what's calling us in the first place.
 *
 * Errors propagate; the helper catches nothing. The wrapper's queue
 * surfaces submit failures via submitNow's own error toast.
 */
export async function applyProposalWrite(
  writer: WriterApi,
  payload: Record<string, any>,
  opts: {
    id: string;
    isCreate: boolean;
    silent?: boolean;
    submitNow?: (opts?: { silent?: boolean }) => Promise<void>;
  },
): Promise<void> {
  if (opts.isCreate) {
    await writer.create({ ...payload, id: opts.id });
  } else {
    await writer.update(opts.id, payload);
  }
  if (!opts.silent) {
    toast.success(actionLabel(writer.mode, opts.isCreate ? 'created' : 'updated'));
  }
  // Auto-flush the wrapper queue to the active block so the change
  // lands in pending_revisions immediately without the user needing
  // a second click. Only when:
  //   - we're not in a silent path (pre-flush would recurse), AND
  //   - the caller wired the proposal context's submitNow through,
  //     meaning we're inside a wrapper with the block lifecycle ready.
  if (!opts.silent && opts.submitNow) {
    // submitNow handles the "no active bundle" case by opening the
    // block picker; that path is non-blocking from here (the picker
    // will resume the flush when the user picks/creates a block).
    await opts.submitNow({ silent: true });
  }
}
