// Builder for the full Foundry-ready feat item — served by
// `/api/module/feats/<dbId>.json`. Used by the Foundry importer at
// embed time to fetch the heavy `system` block (description,
// activities, advancements, uses, requirements, ...) and `effects`
// for the feats the user just picked.
//
// Parallel to `_spellExport.ts`. The split keeps the picker's initial
// fetch lightweight (`_sourceFeatList.ts` returns ~600 bytes/feat) and
// only pays the full-feat cost (~2-5 KB) for the handful of feats the
// user actually selects.
//
// Foundry shape (mirrors what the module's "Export Feat Folder"
// feature produces in the reverse direction — see
// `module/dauligor-pairing/scripts/export-service.js`):
//
//   type: "feat"
//   img:  <CDN URL>
//   system: {
//     type:       { value, subtype },         // feat_type + feat_subtype
//     identifier: "<slug>",                   // feats.identifier
//     description:{ value: <HTML>, chat: "" },// from `description` BBCode
//     requirements: "<text>",                 // feats.requirements
//     properties: [...],                      // includes "repeatable" when set
//     uses: { max, spent, recovery: [...] },  // feats.uses_*
//     activities: { "<aid>": {...}, ... },    // array → keyed-object map
//     advancement: { "<id>":   {...}, ... },  // array → keyed-object map
//     prerequisites: { items: [], repeatable: false },
//     source: { book, page, rules, revision }
//   }
//   effects: [...]
//   flags.dauligor-pairing: { dbId, sourceId, sourceType, ... }

import type { ExportFetchers } from "./_classExport.js";
import {
  getSemanticSourceId,
  denormalizeScalingColumnRow,
  normalizeScaleValueAdvancement,
} from "./_classExport.js";
import { bbcodeToHtml } from "./_bbcode.js";
import {
  collectFeatRequirementReferences,
  buildFeatRequirementLookup,
  renderFeatRequirementText,
} from "./_featRequirements.js";

const parseJsonField = (val: any, fallback: any) => {
  if (val == null) return fallback;
  if (typeof val !== "string") return val;
  try {
    return JSON.parse(val);
  } catch {
    return fallback;
  }
};

const trimString = (val: any) => String(val ?? "").trim();

/**
 * Response payload shape. The `feat` field is the Foundry-ready item
 * that downstream code can hand straight to
 * `actor.createEmbeddedDocuments("Item", [feat])`.
 */
export interface FeatItemBundle {
  kind: "dauligor.feat-item.v1";
  schemaVersion: 1;
  dbId: string;
  sourceId: string;
  feat: {
    name: string;
    type: "feat";
    img?: string;
    system: Record<string, any>;
    effects: unknown[];
    flags: Record<string, any>;
  };
  generatedAt: number;
}

/**
 * Coerce an `advancement` / `activities` field into the Foundry-shape
 * keyed-object map (`{ "<_id>": Advancement, ... }`). dnd5e stores
 * these as `{ <id>: doc }` maps; our DB stores flat arrays. The `_id`
 * key is preserved verbatim from each entry — same convention the
 * `featImport.ts` reverse path uses, so a round-trip stays stable.
 */
function arrayToFoundryMap(entries: any): Record<string, any> {
  // Already-mapped (defensive): if a legacy row stored the dnd5e
  // keyed-object shape directly, pass it through.
  if (entries && typeof entries === "object" && !Array.isArray(entries)) {
    return entries as Record<string, any>;
  }
  const list = Array.isArray(entries) ? entries : [];
  const map: Record<string, any> = {};
  for (let i = 0; i < list.length; i++) {
    const entry = list[i] ?? {};
    const id = trimString(entry?._id);
    // Foundry advancement IDs are 16-char alphanumerics generated by
    // `foundry.utils.randomID()`. We don't mint our own here — if a
    // row is missing `_id` (legacy / authored by hand), fall back to
    // a deterministic-ish synthetic key. The importer's matching is
    // by `flags.dauligor-pairing.sourceId` + name, not these IDs, so
    // a missing `_id` doesn't break re-import.
    const key = id || `adv${String(i).padStart(14, "0")}`;
    map[key] = entry;
  }
  return map;
}

/**
 * The shared Foundry-item shape produced from a `feats`-table row. Backgrounds
 * and races live in the same table (discriminated by `feat_type`), carry the
 * same advancement / description / source machinery, and differ only in the
 * Foundry `type` they map to plus a few type-specific `system` fields. So the
 * core transform is extracted here and reused by `_backgroundExport` /
 * `_raceExport`, which pass their own `foundryType` and then layer their extra
 * fields onto the returned `system`.
 */
export interface FeatLikeItem {
  name: string;
  type: string;
  img?: string;
  system: Record<string, any>;
  effects: unknown[];
  flags: Record<string, any>;
}

export interface BuildFeatLikeOptions {
  /** Foundry Item `type` to stamp — "feat" (default), "background", "race". */
  foundryType?: string;
  /** `flags.dauligor-pairing.entityKind` — defaults to `foundryType`. */
  entityKind?: string;
}

/**
 * Build the shared feat-shaped Foundry item from a `feats`-table row. Returns
 * the `{ name, type, img, system, effects, flags }` object (NOT the bundle
 * envelope) plus the resolved `sourceId`, so callers can wrap it in their own
 * `kind`-tagged bundle and extend `system`. Returns null when no row matches.
 */
export async function buildFeatLikeItem(
  rowId: string,
  fetchers: ExportFetchers,
  opts: BuildFeatLikeOptions = {},
): Promise<{ row: any; item: FeatLikeItem; sourceId: string } | null> {
  const foundryType = opts.foundryType ?? "feat";
  const { fetchDocument, fetchCollection } = fetchers;
  const row: any = await fetchDocument<any>("feats", rowId);
  if (!row) return null;

  const tagIds = parseJsonField(row.tags, []) || [];
  const activitiesArr = Array.isArray(row.activities)
    ? row.activities
    : parseJsonField(row.activities, []) || [];
  const effectsArr = Array.isArray(row.effects)
    ? row.effects
    : parseJsonField(row.effects, []) || [];
  const advancementsArr = Array.isArray(row.advancements)
    ? row.advancements
    : parseJsonField(row.advancements, []) || [];
  const usesRecoveryArr = Array.isArray(row.uses_recovery)
    ? row.uses_recovery
    : parseJsonField(row.uses_recovery, []) || [];

  // Load scaling columns owned by this feat (Phase B of the
  // non-class scaling track). `scaling_columns` is polymorphic via
  // (parent_id, parent_type); when an author adds columns under a
  // feat via the FeatsEditor "Feat Columns" panel, those rows have
  // parent_type='feat' / 'race' / 'background' depending on the
  // feat's featType. Class features (feat_type='class'/'subclass')
  // intentionally have no rows — they inherit from the parent
  // class — so this query simply returns [] for them.
  //
  // The owner parent_type matches the feat's runtime classification:
  // 'feat' / 'race' / 'background'. We map feat_type='monster' to
  // 'feat' since monsters share the generic feat scaling slot today.
  const featTypeForScaling = String(row.feat_type ?? "").toLowerCase();
  const scalingParentType = featTypeForScaling === "race" || featTypeForScaling === "background"
    ? featTypeForScaling
    : (featTypeForScaling === "class" || featTypeForScaling === "subclass")
      ? null // class features don't own scaling
      : "feat"; // 'feat', 'monster', or anything else → generic feat scaling slot
  let scalingColumnsRaw: any[] = [];
  if (scalingParentType) {
    try {
      const rows = await fetchCollection<any>("scaling_columns", {
        where: "parent_id = ? AND parent_type = ?",
        params: [String(row.id), scalingParentType],
        orderBy: "name ASC",
      });
      scalingColumnsRaw = (rows || []).map(denormalizeScalingColumnRow);
    } catch {
      // Defensive: if the query fails (legacy index quirk, etc.),
      // export proceeds without scale normalization. The
      // ScaleValue's raw configuration still ships, and authors can
      // catch broken @scale references in Foundry play.
      scalingColumnsRaw = [];
    }
  }
  // Map column PK -> column row, for the helper to consult.
  const scalingById = Object.fromEntries(
    scalingColumnsRaw.map((column) => [column.id, column]),
  );

  // Normalize each ScaleValue advancement against the loaded columns.
  // The class export pipeline runs the same helper inside its bigger
  // normalize step; for feats the only normalization we need today
  // is ScaleValue, since Trait / ItemGrant / ItemChoice scaling
  // refs are class-features features today. Foundry resolves
  // `@scale.<feat.identifier>.<column-identifier>` automatically
  // from the feat's `system.identifier` once the advancement lands
  // on the item — no module-side wiring required.
  const normalizedAdvancements = advancementsArr.map((adv: any) => {
    if (!adv || typeof adv !== "object") return adv;
    if (trimString(adv.type) === "ScaleValue") {
      return normalizeScaleValueAdvancement(adv, scalingById) || adv;
    }
    return adv;
  });

  const sourceId = trimString(row.identifier) || `feat-${row.id}`;
  const featType = trimString(row.feat_type) || "feat";
  const featSubtype = trimString(row.feat_subtype);

  // Resolve the feat's source FK to its public semantic id for the
  // flag block. Best-effort — a stale FK doesn't break the bundle.
  let featSourceSemanticId: string | null = null;
  let sourceBook = "";
  let sourceRulesVersion = "2014";
  if (row.source_id) {
    const sourceRow: any = await fetchDocument<any>("sources", String(row.source_id));
    if (sourceRow) {
      sourceBook = String(sourceRow.abbreviation || sourceRow.name || "");
      sourceRulesVersion = String(sourceRow.rules_version || "2014");
      featSourceSemanticId = getSemanticSourceId({
        slug: sourceRow.slug,
        abbreviation: sourceRow.abbreviation,
        rules: sourceRow.rules_version || "2014",
      }, sourceRow.id);
    } else {
      featSourceSemanticId = String(row.source_id);
    }
  }

  // Description: BBCode → HTML. Mirrors the spell export. Falls back
  // to an empty string when the BBCode column is empty.
  const descriptionBbcode = trimString(row.description);
  const descriptionHtml = descriptionBbcode ? bbcodeToHtml(descriptionBbcode) : "";

  // Render the requirement tree to text with entity-name resolution,
  // mirroring what the website's FeatDetailPanel does. The lookup is
  // built from THIS feat's tree only (single feat, single fetch round)
  // — much cheaper than the per-source bulk path. Falls back to the
  // legacy `feats.requirements` column when no tree is authored.
  const requirementRefs = collectFeatRequirementReferences([row]);
  const requirementLookup = await buildFeatRequirementLookup(fetchers, requirementRefs);
  const requirementsText = renderFeatRequirementText(row, requirementLookup);

  // `system.properties` is a string array on dnd5e v5 feats. We only
  // surface the `"repeatable"` flag today — additional property tags
  // (e.g. `"mgc"`) aren't persisted on the Dauligor side.
  const properties: string[] = [];
  if (Number(row.repeatable || 0)) properties.push("repeatable");

  const system: Record<string, any> = {
    type: {
      value: featType,
      subtype: featSubtype,
    },
    identifier: sourceId.replace(/^feat-/, ""),
    description: {
      value: descriptionHtml,
      chat: "",
    },
    requirements: requirementsText,
    properties,
    uses: {
      max: trimString(row.uses_max),
      spent: Number(row.uses_spent || 0),
      recovery: Array.isArray(usesRecoveryArr) ? usesRecoveryArr : [],
    },
    // dnd5e expects keyed-object maps for both advancements and
    // activities. See the top-of-file comment for the conversion
    // convention (preserves `_id` keys when present).
    activities: arrayToFoundryMap(activitiesArr),
    advancement: arrayToFoundryMap(normalizedAdvancements),
    prerequisites: {
      items: [],
      repeatable: Number(row.repeatable || 0) ? true : false,
    },
    source: {
      book: sourceBook,
      page: trimString(row.page),
      rules: sourceRulesVersion,
      revision: 1,
      custom: "",
      license: "",
    },
  };

  // Foundry's `feat` schema also has these passive fields. Stamping
  // them at known defaults keeps the imported item validation-clean.
  system.crewed = false;
  system.enchant = {};

  const item: FeatLikeItem = {
    name: String(row.name || ""),
    type: foundryType,
    img: row.image_url || undefined,
    system,
    effects: Array.isArray(effectsArr) ? effectsArr : [],
    flags: {
      "dauligor-pairing": {
        schemaVersion: 1,
        entityKind: opts.entityKind ?? foundryType,
        sourceId,
        dbId: String(row.id),
        // Distinguishes general feats from class-/subclass-features
        // (Foundry stores all three as `type: "feat"` items). See
        // `feat-import-contract.md` § "General Feats vs. Class Features".
        sourceType: String(row.source_type || "feat"),
        featType,
        featSubtype,
        featSpellSourceId: featSourceSemanticId,
        tagIds: Array.isArray(tagIds) ? tagIds.map(String) : [],
      },
    },
  };

  return { row, item, sourceId };
}

/**
 * Build the full Foundry-ready feat item bundle for one feat row.
 * Thin wrapper over `buildFeatLikeItem` (foundryType = "feat").
 *
 * Returns null when no row matches.
 */
export async function buildFeatItemBundle(
  featId: string,
  fetchers: ExportFetchers,
): Promise<FeatItemBundle | null> {
  const built = await buildFeatLikeItem(featId, fetchers, { foundryType: "feat" });
  if (!built) return null;
  return {
    kind: "dauligor.feat-item.v1",
    schemaVersion: 1,
    dbId: String(built.row.id),
    sourceId: built.sourceId,
    feat: { ...built.item, type: "feat" },
    generatedAt: Date.now(),
  };
}
