import sqlite3, sys
db = sqlite3.connect(sys.argv[1])
cur = db.cursor()
def q(sql):
    return cur.execute(sql).fetchone()[0]

print("=== Phase 1 D1 row counts and FK integrity ===")
print()
print("Section 1: Sources")
print(f"  sources                            {q('SELECT COUNT(*) FROM sources')}")
print()
print("Section 2: Taxonomy")
print(f"  tag_groups                         {q('SELECT COUNT(*) FROM tag_groups')}")
print(f"  tags                               {q('SELECT COUNT(*) FROM tags')}")
print(f"    tags with bad group_id:          {q('SELECT COUNT(*) FROM tags t LEFT JOIN tag_groups g ON t.group_id=g.id WHERE g.id IS NULL')}")
print()
print("Section 3: Equipment categories")
print(f"  armor_categories                   {q('SELECT COUNT(*) FROM armor_categories')}")
print(f"  weapon_categories                  {q('SELECT COUNT(*) FROM weapon_categories')}")
print(f"  weapon_properties                  {q('SELECT COUNT(*) FROM weapon_properties')}")
print(f"  tool_categories                    {q('SELECT COUNT(*) FROM tool_categories')}")
print(f"  language_categories                {q('SELECT COUNT(*) FROM language_categories')}")
print(f"  languages                          {q('SELECT COUNT(*) FROM languages')}")
print(f"    langs with bad category_id:      {q('SELECT COUNT(*) FROM languages l LEFT JOIN language_categories lc ON l.category_id=lc.id WHERE l.category_id IS NOT NULL AND lc.id IS NULL')}")
print()
print("Section 4: Mechanical tokens")
print(f"  attributes                         {q('SELECT COUNT(*) FROM attributes')}")
print(f"  damage_types                       {q('SELECT COUNT(*) FROM damage_types')}")
print(f"  condition_categories               {q('SELECT COUNT(*) FROM condition_categories')}")
print()
print("Section 5: Status conditions")
print(f"  status_conditions                  {q('SELECT COUNT(*) FROM status_conditions')}")
print()
print("Section 6: Specialized proficiencies")
print(f"  skills                             {q('SELECT COUNT(*) FROM skills')}")
print(f"    skills with bad ability_id:      {q('SELECT COUNT(*) FROM skills s LEFT JOIN attributes a ON s.ability_id=a.id WHERE s.ability_id IS NOT NULL AND a.id IS NULL')}")
print(f"  tools                              {q('SELECT COUNT(*) FROM tools')}")
print(f"    tools with bad category_id:      {q('SELECT COUNT(*) FROM tools t LEFT JOIN tool_categories tc ON t.category_id=tc.id WHERE t.category_id IS NOT NULL AND tc.id IS NULL')}")
print(f"    tools with bad ability_id:       {q('SELECT COUNT(*) FROM tools t LEFT JOIN attributes a ON t.ability_id=a.id WHERE t.ability_id IS NOT NULL AND a.id IS NULL')}")
print(f"  weapons                            {q('SELECT COUNT(*) FROM weapons')}")
print(f"    weapons with bad category_id:    {q('SELECT COUNT(*) FROM weapons w LEFT JOIN weapon_categories wc ON w.category_id=wc.id WHERE w.category_id IS NOT NULL AND wc.id IS NULL')}")
print(f"  armor                              {q('SELECT COUNT(*) FROM armor')}")
print(f"    armor with bad category_id:      {q('SELECT COUNT(*) FROM armor a LEFT JOIN armor_categories ac ON a.category_id=ac.id WHERE a.category_id IS NOT NULL AND ac.id IS NULL')}")
print()
print("Section 7: Spellcasting foundation")
print(f"  spellcasting_types                 {q('SELECT COUNT(*) FROM spellcasting_types')}")
print(f"  spellcasting_progressions (all)    {q('SELECT COUNT(*) FROM spellcasting_progressions')}")
sql_std = "SELECT COUNT(*) FROM spellcasting_progressions WHERE type='standard'"
sql_pact = "SELECT COUNT(*) FROM spellcasting_progressions WHERE type='pact'"
sql_known = "SELECT COUNT(*) FROM spellcasting_progressions WHERE type='known'"
print(f"    type=standard                    {q(sql_std)}")
print(f"    type=pact                        {q(sql_pact)}")
print(f"    type=known                       {q(sql_known)}")
print(f"  multiclass_master_chart            {q('SELECT COUNT(*) FROM multiclass_master_chart')}")
print()
print("Section 8: Modular options")
print(f"  unique_option_groups               {q('SELECT COUNT(*) FROM unique_option_groups')}")
print(f"  unique_option_items                {q('SELECT COUNT(*) FROM unique_option_items')}")
print(f"    items with bad group_id:         {q('SELECT COUNT(*) FROM unique_option_items i LEFT JOIN unique_option_groups g ON i.group_id=g.id WHERE i.group_id IS NOT NULL AND g.id IS NULL')}")
print()
print("Section 9: Image metadata")
print(f"  image_metadata                     {q('SELECT COUNT(*) FROM image_metadata')}")
