-- Add a structured `proficiencies` column to `backgrounds`.
--
-- Backgrounds grant skill / tool / language proficiencies (and, in the 2024
-- rules, ability-score increases + an origin feat). The 5etools-sourced data
-- carries these only as prose in the description's `[ul]` block, which we were
-- re-parsing on every render. This column stores them as STRUCTURED data,
-- populated once at import and editable via the dedicated Proficiencies section
-- — the source of truth the view renders from and the exporter turns into real
-- dnd5e advancements (Trait / AbilityScoreImprovement / ItemGrant).
--
-- Shape (JSON; see src/lib/backgroundProficiencies.ts):
--   {
--     abilityScores: string[],                       // ability keys (2024)
--     feat: string,                                  // origin feat id/slug (2024)
--     skills:    { granted: string[], choices: [{count, pool: string[]}] },
--     tools:     { granted: string[], choices: [{count, pool: string[]}] },
--     languages: { granted: string[], choices: [{count, pool: string[]}] }
--   }
-- granted/pool hold the skills/tools/languages table identifiers (the
-- dnd5e-aligned keys: his, cartographer, common). pool [] = "any of category".
--
-- Default '{}' (empty object) — pre-existing rows read as "no structured
-- proficiencies yet" and the view falls back to parsing the prose block until
-- they're re-imported. Must be added to queryD1's jsonFields list so reads
-- come back parsed.
--
-- D1 NOTE: no user BEGIN/COMMIT/PRAGMA — D1 wraps each migration atomically.

ALTER TABLE backgrounds ADD COLUMN proficiencies TEXT DEFAULT '{}';
