name = "dauligor-storage"
main = "index.js"
compatibility_date = "2026-04-26"
preview_urls = false

[vars]
R2_PUBLIC_URL = "https://images.dauligor.com"

[observability]
enabled = true

[observability.logs]
enabled = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dauligor-storage"

[[d1_databases]]
binding = "DB"
database_name = "dauligor-db"
database_id = "25a9d61a-29ec-42c7-9dae-8cde8d88913d"
migrations_dir = "migrations"
